### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by sandamicke** [mazkolain-zz/spotimc#122] opened 2013-07-18 10:05 UTC
I havent been able to log in since it crash all the time after i insert my name and password.
I am using latest XBMC on my rasperry PI
Dont know what's wrong 

Sandamicke

**Comment by mazkolain-zz** [comment] 2013-07-19 19:09
Hello,

Which raspberry PI XBMC distro are you using? I have no issues with Raspbmc running XBMC 12.2. Also, a pastebin of a log file generated by this crash would help a lot.

Regards,

**Comment by sandamicke** [comment] 2013-07-20 09:51
Actually I dont know where to find that out :) But its the new red backgroud.

**Comment by burczyk** [comment] 2013-08-02 20:23
I have the same problem. After login sometimes I can see spotimc tabs and after a few seconds the whole system crashes. 
tail -f xbmc.log shows this:
http://pastebin.com/QiTa958H#

Any idea what can be wrong?

EDIT:
Here's the second log from console up to the restart:
http://pastebin.com/JvX0duX1

**Comment by sandamicke** [comment] 2013-08-03 09:11
I reinstalled the system and installed spotiMC first of all and now it works

//Micke

2 aug 2013 kl. 22:25 skrev "Kamil Burczyk" notifications@github.com:

**Comment by mazkolain-zz** [comment] 2013-08-03 10:34
@burczyk, @sandamicke have you set up playlists as the default view from Spotimc's config? There were some similar issues back in beta3.

**Comment by sandamicke** [comment] 2013-08-03 10:37
When it started I changed that in the menu so now it starts in my playlist ;)

//Micke

3 aug 2013 kl. 12:34 skrev "Mikel Azkolain" notifications@github.com:

**Comment by OlaPalholmen** [comment] 2013-08-06 22:13
Same issue using XBian 1.0 Beta 1.1 XBMC 12.1 with a fresh install 
After a successful login xbmc dies.
tail shows http://pastebin.com/b0CrTXUd

edit: crash still occurs when startup screen is My playlist instead of New stuff

**Comment by burczyk** [comment] 2013-08-07 06:31
@mazkolain where can I set default view? In spotimc itself or somewhere in system settings/plugin settings? Right now I am unable to launch spotimc so any change inside is impossible.

In the meantime I also installed XBMC on another SD card (which is slower - it has about 4MB/s) and here spotimc worked on the same RPi hardware and the same XBMC version. Strange thing...

**Comment by sandamicke** [comment] 2013-08-07 06:38
In the top menu there is a settings option

//Micke

7 aug 2013 kl. 08:31 skrev "Kamil Burczyk" notifications@github.com:

**Comment by burczyk** [comment] 2013-08-07 06:47
@sandamicke as I said I am unable to start spotimc, because it crashes the whole XBMC after a second or two. So any change using GUI is impossible. Can I change these settings in some kind of configuration file?

**Comment by OlaPalholmen** [comment] 2013-08-07 20:08
@burczyk Press menu button on your remote when you spotimc is selected before you start it. You will se an option "Add-on settings".

**Comment by mazkolain-zz** [comment] 2013-08-07 21:34
@etmot thanks for the addon settings tip. Sadly it will always crash, regardless the startup view chosen.

@burczyk so you get no issues on a lower class SD card (also using the same XBMC distro?). I can reproduce the issue on a class 10 card, but I will give a try on a slower one (class 6 cards seem unaffected).

**Comment by burczyk** [comment] 2013-08-08 08:28
@mazkolain exactly! On SD card class 10 it crashes each time. On SD card class 4 it works slow as hell but it works. Maybe today I'll try to reinstall the whole Raspbmc on SD class 10 and start with fresh spotimc install.

**Comment by Porzeczek** [comment] 2013-08-11 08:20
I've replaced libspotify.so to newest version from https://developer.spotify.com/technologies/libspotify/ and now spotimc works :)
On Xbian this lib is in /home/xbian/.xbmc/addons/script.audio.spotimc/resources/dlls/linux/armv6hf

**Comment by mazkolain-zz** [comment] 2013-08-12 13:34
@Porzeczek thanks for finding this out! It looks like I put the wrong libspotify binary on the beta4 release. Replacing the existing libspotify.so file with the one in the latest release fixes the issue.

Closing this issue, as the correct libspotify binary will be included on the next release.

**Closed as completed by mazkolain-zz** 2013-08-12 13:34 UTC
