### ISSUE TITLE
Startup state is not flexible

### ISSUE THREAD

**Issue by joostvunderink** [mazkolain-zz/spotimc#43] opened 2012-06-15 22:58 UTC
When I open spotimc, "new stuff" is the first thing that I see. However, I am not interested in Justin Bieber's new track.

It would be good either to be able to configure the tab that gets shown when you start spotimc, or if spotimc remembered its state from the previous time it was used.

**Comment by mazkolain-zz** [comment] 2012-06-26 21:10
Hi @joostvunderink,

First of all thank you for reporting the issues (OMG six issues in a row!). They are very helpful!

This issue in particular is a duplicate of #4 which was closed in beta1, but anyway, would be nice to implement "a remember last state". Thanks!

**Closed as completed by mazkolain-zz** 2012-06-26 21:10 UTC
