### ISSUE TITLE
Script failed

### ISSUE THREAD

**Issue by KristofferBerge** [mazkolain-zz/spotimc#14] opened 2012-04-01 11:59 UTC
Every time i start the app it says script failed and just keeps on loading.

**Comment by mazkolain-zz** [comment] 2012-04-05 19:01
Hi Berge,

Could yo please provide a copy of XBMC's log file? Thanks!

**Comment by chrillep** [comment] 2012-04-05 20:33
i removed all my addon-ons and reinstalled them seems like trakutilitirs is a big thief when it comes to crashing other addons.

**Comment by bass000** [comment] 2012-04-09 15:04
Be sure to use these downloads links to install (not github zip)
https://github.com/mazkolain/spotimc/downloads

**Comment by Bnicke** [comment] 2012-04-17 17:23
I have the same problem.. I use Vista.
Here´s my log: http://nedladdning.bergstrom.se/xbmc.log

I made this change (hardcoded the path) in default.py and then it worked a bit further:
#**addon_path** = addon_cfg.getAddonInfo('path')
**addon_path** = 'C:/Users/FAMBER~1/AppData/Roaming/XBMC/addons/script.audio.spotimc/'

My username is "Fam Bergström", the swedish national character seems to mess things up.. 
It almost works.. the plug downloaded something but then it wants me to restart XBMC even after I restarted it..

**Comment by mazkolain-zz** [comment] 2012-04-24 12:44
Thanks @Bnicke for pointing out the character issue. Let's see if I'm able to reproduce it with any non-ascii character on the username (I believe that Windows should be using unicode path names)...

**Comment by mazkolain-zz** [comment] 2012-06-01 18:47
It seems that python does not have support for unicode import paths, and thus the addon fails because it has to load some packages on the user's home folder.

It got fixed in python 3.2 (Most of the XBMC installations use python 2.6 at the time of writing):
http://bugs.python.org/issue9425

Closing it as wontfix.

**Closed as completed by mazkolain-zz** 2012-06-01 18:47 UTC
Labels: wontfix
