### ISSUE TITLE
Spotimc on FreeBSD/PC-BSD 

### ISSUE THREAD

**Issue by bkupidura** [mazkolain-zz/spotimc#136] opened 2013-11-24 13:40 UTC
Spotimc crash after start on BSD system.

Env:
FreeBSD: 9.1
XBMC: 12.2
Spotimc: 1-0-beta4
Python: 2.7.5

Python trace:
14:35:53 T:34709142528  NOTICE: -->Python Interpreter Initialized<--
14:35:54 T:34709142528  NOTICE: /home/xbmc/.xbmc/addons/skin.confluence/write_test.txt
14:35:54 T:34709142528   ERROR: /home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/fonts.py:140: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
14:35:55 T:34709142528  NOTICE: /home/xbmc/.xbmc/addons/skin.confluence/write_test.txt
14:35:55 T:34709142528  NOTICE: install include: /home/xbmc/.xbmc/addons/script.audio.spotimc/resources/skins/DefaultSkin/720p/includes.xml
14:35:55 T:34619814912   ERROR: ClearBlock: Trying to clear non existent block /home/xbmc/.xbmc/addons/script.audio.spotimc
14:36:03 T:34709142528   ERROR: Previous line repeats 2 times.
14:36:03 T:34709142528   ERROR: Traceback (most recent call last):
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/default.py", line 75, in <module>
14:36:03 T:34709142528   ERROR:     main(**addon_path**)
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/spotimcgui/**init**.py", line 374, in main
14:36:03 T:34709142528   ERROR:     initially_unload_playlists=False,
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/spotify/session.py", line 312, in **init**
14:36:03 T:34709142528   ERROR:     err = self.**session_interface.create(ctypes.byref(config), ctypes.byref(self.__session_struct))
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/session.py", line 129, in create
14:36:03 T:34709142528   ERROR:     ctypes.POINTER(config), ctypes.POINTER(ctypes.c_void_p)
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init**.py", line 95, in _get_func
14:36:03 T:34709142528   ERROR:     return self._get_func2(name, name, restype, *argtypes)
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 85, in _get_func2
14:36:03 T:34709142528   ERROR:     lib = self.get_library()
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 66, in get_library
14:36:03 T:34709142528   ERROR:     self.**library = self._load_library()
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init**.py", line 111, in _load_library
14:36:03 T:34709142528   ERROR:     return ll.load('libspotify')
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 209, in load
14:36:03 T:34709142528   ERROR:     _library_cache[name] = self._load(name)
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 203, in _load
14:36:03 T:34709142528   ERROR:     return self._load_from_sys_path(loader, name)
14:36:03 T:34709142528   ERROR:   File "/home/xbmc/.xbmc/addons/script.audio.spotimc/resources/libs/PyspotifyCtypes.egg/_spotify/__init__.py", line 174, in _load_from_sys_path
14:36:03 T:34709142528   ERROR:     full_path = os.path.join(path, filename)
14:36:03 T:34709142528   ERROR:   File "/usr/local/lib/python2.7/posixpath.py", line 75, in join
14:36:03 T:34709142528   ERROR:     if b.startswith('/'):
14:36:03 T:34709142528   ERROR: AttributeError: 'NoneType' object has no attribute 'startswith'
14:36:03 T:34619814912   ERROR: ClearBlock: Trying to clear non existent block /home/xbmc/.xbmc/addons/script.audio.spotimc
14:36:04 T:34676577280   ERROR: Previous line repeats 2 times.
14:36:04 T:34676577280  NOTICE: Thread Background Loader start, auto delete: false
14:36:04 T:34709142528  NOTICE: Previous line repeats 1 times.
14:36:04 T:34709142528   ERROR: Exception
14:36:04 T:34709142528   ERROR: AttributeError
14:36:04 T:34709142528   ERROR: :
14:36:04 T:34709142528   ERROR: "'NoneType' object has no attribute 'startswith'"
14:36:04 T:34709142528   ERROR:  in
14:36:04 T:34709142528   ERROR: <bound method ?.? of <spotify.session.Session instance at 0x814b08950>>
14:36:04 T:34709142528   ERROR:  ignored
14:36:04 T:34619814912   ERROR: ClearBlock: Trying to clear non existent block /home/xbmc/.xbmc/addons/script.audio.spotimc

**Comment by mazkolain-zz** [comment] 2013-11-26 19:25
Hi,

Marking this issue as a duplicate of https://github.com/mazkolain/spotimc/issues/105.

Anyway, thanks for reporting!

**Closed as completed by mazkolain-zz** 2013-11-26 19:25 UTC
