### ISSUE TITLE
Won't advance to next track.

### ISSUE THREAD

**Issue by adamoc** [mazkolain-zz/spotimc#89] opened 2013-01-26 11:50 UTC
It doesn't advance to next track on Raspberry Pi running libspofity 12.1.103 beta. The progress bar stays in thr position of the length of the previous track.

**Comment by pmiossec** [comment] 2013-01-26 19:41
Same for me :(

edit:
In fact, after some tests, it's perhaps not the fault of spotimc.
For me it was on a new install of the last version of raspbmc on my Pi.
But I just saw that I have the same problem with another xbmc plugin ( Qobuz xbmc)...
So, I think that's perhaps a xbmc problem (or less likely a raspbmc one)
Some have the same problem here but the message is not clear so I don't understand where the problem come from!
http://forum.stmlabs.com/showthread.php?tid=5920

**Comment by andrewl** [comment] 2013-01-28 21:55
Same here, although pressing Stop and then manually advancing to the next track works just fine. The logfile consists of a lot of repeated messages like this:

21:49:12 T:2854528064 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
21:49:12 T:2854528064   FATAL: CDVDMessageQueue(player)::Get MSGQ_NOT_INITIALIZED
21:49:12 T:2720379968   FATAL: Previous line repeats 34 times.

as per https://gist.github.com/4659479

**Comment by andrewl** [comment] 2013-01-28 22:15
Sorry, looks like a dupe of this: https://github.com/mazkolain/spotimc/issues/88

An update to the nightly build of raspbmc fixed this problem.

**Comment by pmiossec** [comment] 2013-01-29 09:01
@adamoc We are now sure that's a raspbmc problem. Could you close this issue?

**Comment by mazkolain-zz** [comment] 2013-01-30 21:05
Closing this issue as suggested.

Anyway, the process that serves as a bridge between libspotify and XBMC is quite resource hungry (in both memory and CPU usage), so this component may still need some optimizations to run fine on the pi.

**Closed as completed by mazkolain-zz** 2013-01-30 21:05 UTC
