### ISSUE TITLE
see my photos while listening to music

### ISSUE THREAD

**Issue by nickeeee** [mazkolain-zz/spotimc#85] opened 2013-01-13 13:02 UTC
Fix so I can see my photos while listening to music. ( in the menu :D)

**Comment by mazkolain-zz** [comment] 2013-01-13 16:14
Hi,

This is a duplicate of https://github.com/mazkolain/spotimc/issues/28.

SInce Spotimc is a script rather than a plugin, there are some limitations that prevent it from running in the background.

Anyway, thanks for the feedback!

**Closed as completed by mazkolain-zz** 2013-01-13 16:14 UTC
Labels: duplicate
