### ISSUE TITLE
SpotiMC Crashes Frodo Openelec 3.0 RC1

### ISSUE THREAD

**Issue by Glazzanz** [mazkolain-zz/spotimc#84] opened 2013-01-04 02:36 UTC
When opening prompted get the 'loading' screen, when xbmc crashes.

15:30:55 T:140560187148096  NOTICE: Running the application...
15:30:56 T:140560187148096  NOTICE: ES: Starting event server
15:30:56 T:140559515645696  NOTICE: Thread CEventServer start, auto delete: false
15:30:56 T:140559515645696  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
15:30:56 T:140559515645696  NOTICE: UDP: Listening on port 9777
15:30:56 T:140559507252992  NOTICE: Thread CTCPServer start, auto delete: false
15:30:56 T:140560187148096  NOTICE: starting zeroconf publishing
15:30:56 T:140559490467584  NOTICE: Thread Jobworker start, auto delete: true
15:30:56 T:140559853565696  NOTICE: Thread CRssReader start, auto delete: false
15:30:59 T:140559477880576  NOTICE: Thread Background Loader start, auto delete: false
15:32:51 T:140559490467584  NOTICE: Previous line repeats 2 times.
15:32:51 T:140559490467584  NOTICE: Thread XBPyThread start, auto delete: false
15:32:51 T:140559490467584  NOTICE: -->Python Interpreter Initialized<--
15:32:51 T:140559490467584  NOTICE: /storage/.xbmc/addons/skin.confluence/write_test.txt
15:32:51 T:140559490467584   ERROR: /storage/.xbmc/addons/script.audio.spotimc/resources/libs/XbmcSkinUtils.egg/skinutils/fonts.py:138: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
15:32:51 T:140559490467584  NOTICE: /storage/.xbmc/addons/skin.confluence/write_test.txt
15:32:51 T:140559490467584  NOTICE: install include: /storage/.xbmc/addons/script.audio.spotimc/resources/skins/DefaultSkin/720p/includes.xml
15:32:52 T:140560187148096   ERROR: ClearBlock: Trying to clear non existent block /storage/.xbmc/addons/script.audio.spotimc
15:32:53 T:140559490467584   ERROR: Previous line repeats 2 times.
15:32:53 T:140559490467584  NOTICE: port: 8080
15:32:53 T:140559063402240  NOTICE: libspotify log: 02:32:53.624 I [ap:1752] Connecting to AP ap.spotify.com:4070

**Comment by Glazzanz** [comment] 2013-01-04 02:41
Appears to be the same, or similar to: https://github.com/mazkolain/spotimc/issues/82

**Comment by mazkolain-zz** [comment] 2013-01-04 18:00
Hello,

It initially seemed to be the same as #82, but I tested against the latest Frodo master on Linux and everything looks fine.

Perhaps you are using Openelec? There's nothing wrong with Openelec, but there are some known issues with Spotimc on it, when started with cache disabled.

**Comment by Glazzanz** [comment] 2013-01-04 18:11
Hi, Yes I am using the RC1 version of Openelec (so Frodo RC3).  Although I had no issues on Beta 6.  

Is the cache disabled by default - this was a fresh installation.

Sorry for the false alarm...

**Comment by mazkolain-zz** [comment] 2013-01-04 21:12
Well, perhaps it's not a false alarm and you found a new bug. If it happens everytime you start Spotimc there's definitely something wrong there.

Will try to test with the latest RC of Openelec, and see what happens.

Thanks for reporting!

**Comment by mazkolain-zz** [comment] 2013-01-30 21:23
It finally turned out to be a duplicate of #76 so I'm closing this one, though many thanks for all the feedback.

**Closed as completed by mazkolain-zz** 2013-01-30 21:23 UTC
Labels: bug, duplicate
