### ISSUE TITLE
spotimc keeps asking me to restart xbmc

### ISSUE THREAD

**Issue by asgerhallas** [mazkolain-zz/spotimc#1] opened 2012-03-13 18:42 UTC
Everytime a start the addon I get a popup saying I need to restart. I have restarted several times, restarted the computer, and reinstalled the plugin to no avail. 

I can mail you the logs if you like, I don't know which parts are the interesting ones.

**Comment by asgerhallas** [comment] 2012-03-13 18:49
It happens on both alpha3 and alpha4

**Comment by asgerhallas** [comment] 2012-03-13 19:02
And here's the logs: http://pastebin.com/ttjeJw9D

**Comment by mazkolain-zz** [comment] 2012-03-13 20:05
That's a strange bug. A couple of questions:
- Do you see the same popup message or it was initially a different one?
- Are you using an admin account or an unprivileged one? (both should work)

I was unable get any clue from your logs. The code involved in that issue does't seem to post useful debug info. I'll take a closer look and try to reproduce it.

Thank you for the report!

**Comment by asgerhallas** [comment] 2012-03-13 21:08
Thanks for replying so quick.

1) the full story is, that I had xbmc v10 installed, and did not see the notice about requiring Eden at first. I installed spotimc in v10 and it told me it would download the additional resources, but it then of course failed because of the version requirement. I then removed xbmc and installed Eden and then spotimc again. And as soon as I started the plugin I got the message about restarting xbmc. I have searched for setting and other left overs from spotimc from the last version, but I haven't found anything. I might not know what to look for though.

2) i'm on an aministrator account

**Comment by Dedas** [comment] 2012-03-30 19:23
I have the same problem as asgerhallas. Installed Spotimc on 10.1 and then upgraded to 11.0, stuck with the restart message. Any clues?

**Comment by mazkolain-zz** [comment] 2012-04-01 08:37
Hi Dedas,

It's probably because the Confluence skin got copied to your userdata folder (by Spotimc running on XBMC 10.1), and now that XBMC was upgraded (comes with a new version of the confluence skin) it will pick the newer version (which is on the XBMC's bin folder). This is what is causing Spotimc to enter in an endless you-need-to-restart loop (Spotimc's fault, it should check for this).

Deleting the old confluence skin on the userdata folder will do the trick. A fix for this issue will be included on the next alpha.

**Comment by Dedas** [comment] 2012-04-01 14:28
Thank you! That solved it! :D

**Comment by asgerhallas** [comment] 2012-04-01 14:30
I could not find any skin files in my userdata folder, so I ended up removing all xbmc data from the library and reinstalled Eden. That worked. 

And this plugin was worth the hazzle! Very well designed and usable :)

**Comment by mazkolain-zz** [comment] 2012-04-02 21:24
Closing this issue. A fix was committed to the [skinutils](https://github.com/mazkolain/xbmc-skinutils) repo.

**Closed as completed by mazkolain-zz** 2012-04-02 21:24 UTC
Labels: bug
